linters:
  enable:
    - gofmt
    - govet
    - gocyclo
    - ineffassign
    - misspell
    - revive
    - gosimple
    - staticcheck
    - typecheck
    - unused
    - errcheck
    - gosec

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
