version: '3.8'

services:
  insider-monitor:
    build: .
    volumes:
      - ./config.json:/app/config.json
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - TZ=UTC
    command: ["-config", "/app/config.json"] 