title: Solana Insider Monitor
description: Documentation for monitoring Solana wallet activities and balance changes
theme: just-the-docs

# Set a baseurl if your site is running in a virtual subdirectory
baseurl: "/Insider-Monitor"
url: "https://accursedgalaxy.github.io"

# Auxiliary links for the upper right navigation
aux_links:
  "View on GitHub":
    - "//github.com/accursedgalaxy/Insider-Monitor"
aux_links_new_tab: true

# Theme settings
logo: "/assets/images/logo.svg"
favicon_ico: "/assets/images/favicon.svg"
color_scheme: light

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2023 AccursedGalaxy. Distributed under the <a href=\"https://github.com/accursedgalaxy/Insider-Monitor/blob/main/LICENSE\">MIT license</a>"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer "Edit this page on GitHub" link
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/accursedgalaxy/Insider-Monitor"
gh_edit_branch: "feat/web-ui"
gh_edit_path: "docs/"

# Enable or disable the site search
search_enabled: true

# Enable or disable heading anchors
heading_anchors: true

# Google Analytics tracking ID
ga_tracking:
ga_tracking_anonymize_ip: true

# Plugins
plugins:
  - jekyll-seo-tag
