title: Solana Insider Monitor
description: Documentation for monitoring Solana wallet activities and balance changes
remote_theme: just-the-docs/just-the-docs
color_scheme: light

# Theme configuration
logo: "/assets/images/logo.svg"
favicon_ico: "/assets/images/favicon.svg"

# CSS
sass:
  style: :compressed # or :expanded for debugging
  sass_dir: assets/css

# Enable or disable the site search
search_enabled: true
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "//github.com/accursedgalaxy/Insider-Monitor"

aux_links_new_tab: true

# Footer content
footer_content: "Copyright &copy; 2023 AccursedGalaxy. Distributed under the <a href=\"https://github.com/accursedgalaxy/Insider-Monitor/blob/main/LICENSE\">MIT license.</a>"

# Collections for website structure
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

# Enable or disable heading anchors
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer "Edit this page on GitHub" link
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/accursedgalaxy/Insider-Monitor"
gh_edit_branch: "main"
gh_edit_path: "docs/"

# Google Analytics
ga_tracking:
ga_tracking_anonymize_ip: true
