name: docs
on:
  push:
    branches:
      - master
      - main
      - feat/web-ui

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for git-revision-date-localized plugin

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache

      # Install all required dependencies for mkdocs.yml
      - name: Install MkDocs and plugins
        run: |
          pip install mkdocs-material>=9.4.0
          pip install pillow cairosvg
          pip install mkdocs-minify-plugin
          pip install mkdocs-git-revision-date-localized-plugin
          pip install pymdown-extensions

          # Create CSS directory if it doesn't exist
          mkdir -p docs/assets/css
          # Only create custom.css if it doesn't exist
          if [ ! -f "docs/assets/css/custom.css" ]; then
            echo "/* Custom styles for documentation */" > docs/assets/css/custom.css
          fi

          # Only create extra.js if it doesn't exist
          if [ ! -f "docs/assets/js/extra.js" ]; then
            echo "/* Custom JavaScript for documentation */" > docs/assets/js/extra.js
          fi

          # Set environment variable for Google Analytics if needed
          if [ -n "${{ vars.GOOGLE_ANALYTICS_KEY }}" ]; then
            echo "GOOGLE_ANALYTICS_KEY=${{ vars.GOOGLE_ANALYTICS_KEY }}" >> $GITHUB_ENV
          fi

      - name: Deploy documentation
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

          mkdocs gh-deploy --force --config-file mkdocs.yml
