name: docs
on:
  push:
    branches:
      - master
      - main
      - feat/web-ui

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for git-revision-date-localized plugin

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache

      # Install all required dependencies for mkdocs.yml
      - name: Install MkDocs and plugins
        run: |
          pip install mkdocs-material==9.5.9
          pip install pillow cairosvg
          pip install mkdocs-minify-plugin
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mkdocs-social-plugin
          pip install pymdown-extensions
          pip install mkdocs-material-extensions

          # Create required directories if they don't exist
          mkdir -p docs/assets/css docs/assets/js
          touch docs/assets/css/custom.css
          touch docs/assets/js/extra.js

          # Set environment variable for Google Analytics if needed
          if [ -n "${{ vars.GOOGLE_ANALYTICS_KEY }}" ]; then
            echo "GOOGLE_ANALYTICS_KEY=${{ vars.GOOGLE_ANALYTICS_KEY }}" >> $GITHUB_ENV
          fi

      - name: Deploy documentation
        run: mkdocs gh-deploy --force
